In [ ]:
import pandas as pd
import numpy as np

# International Scorecard for Select Countries

In [ ]:
df = pd.read_excel('/content/International Scorecard for Select Countries.xlsx', header = 1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        21 non-null     object
 1   Year                           21 non-null     int64
 2   LPI Rank                       21 non-null     int64
 3   LPI Score                      21 non-null     float64
 4   Customs Rank                   21 non-null     int64
 5   Customs Score                  21 non-null     float64
 6   Infrastructure Rank            21 non-null     int64
 7   Infrastructure Score           21 non-null     float64
 8   International shipments Rank   21 non-null     int64
 9   International shipments Score  21 non-null     float64
 10  Logistics competence Rank      21 non-null     int64
 11  Logistics competence Score     21 non-null     float64
 12  Tracking & tracing Rank        21 non-null     int64
 13  Tracking & tracing Score       21 non-null     float64
 14  Timeliness Rank                21 non-null     int64
 15  Timeliness Score               21 non-null     float64
dtypes: float64(7), int64(8), object(1)
memory usage: 2.8+ KB

In [ ]:
df.Country.unique()

array(['Australia', 'Belgium', 'Brazil', 'Canada', 'China', 'Finland',
       'France', 'Germany', 'Hong Kong SAR, China', 'India', 'Indonesia',
       'Japan', 'Malaysia', 'Mexico', 'Netherlands', 'Philippines',
       'Singapore', 'Thailand', 'United Arab Emirates', 'United Kingdom',
       'United States'], dtype=object)

In [ ]:
mapping = {
    'Australia': 'AUS',
    'Belgium': 'BEL',
    'Brazil': 'BRA',
    'Canada': 'CAN',
    'China': 'CHN',
    'Finland': 'FIN',
    'France': 'FRA',
    'Germany': 'DEU',
    'Hong Kong SAR, China': 'HKG',
    'India': 'IND',
    'Indonesia': 'IDN',
    'Japan': 'JPN',
    'Malaysia': 'MYS',
    'Mexico': 'MEX',
    'Netherlands': 'NLD',
    'Singapore': 'SGP',
    'Thailand': 'THA',
    'United Arab Emirates': 'ARE',
    'United Kingdom': 'GBR',
    'United States': 'USA'

}

In [ ]:
len(mapping)

20

In [ ]:
df['country_code'] = df.Country.replace(mapping)

In [ ]:
df.head()

,Country,Year,LPI Rank,LPI Score,Customs Rank,Customs Score,Infrastructure Rank,Infrastructure Score,International shipments Rank,International shipments Score,Logistics competence Rank,Logistics competence Score,Tracking & tracing Rank,Tracking & tracing Score,Timeliness Rank,Timeliness Score,country_code
0,Australia,2023,19,3.7,14,3.7,9,4.1,47,3.1,14,3.9,11,4.1,35,3.6,AUS
1,Belgium,2023,7,4.0,7,3.9,9,4.1,4,3.8,3,4.2,16,4.0,4,4.2,BEL
2,Brazil,2023,51,3.2,56,2.9,47,3.2,68,2.9,46,3.3,54,3.2,46,3.5,BRA
3,Canada,2023,7,4.0,4,4.0,3,4.3,14,3.6,3,4.2,11,4.1,10,4.1,CAN
4,China,2023,19,3.7,31,3.3,14,4.0,14,3.6,20,3.8,23,3.8,30,3.7,CHN

In [ ]:
df.drop(
    ['LPI Rank', 'LPI Score', 'Customs Rank', 'Infrastructure Rank', 'International shipments Rank', 'Logistics competence Rank', 'Tracking & tracing Rank', 'Timeliness Rank'],
    axis=1, inplace=True
)

In [ ]:
df.drop('Country', axis=1, inplace = True)

In [ ]:
df.head()

,Year,Customs Score,Infrastructure Score,International shipments Score,Logistics competence Score,Tracking & tracing Score,Timeliness Score,country_code
0,2023,3.7,4.1,3.1,3.9,4.1,3.6,AUS
1,2023,3.9,4.1,3.8,4.2,4.0,4.2,BEL
2,2023,2.9,3.2,2.9,3.3,3.2,3.5,BRA
3,2023,4.0,4.3,3.6,4.2,4.1,4.1,CAN
4,2023,3.3,4.0,3.6,3.8,3.8,3.7,CHN

In [ ]:
df.rename(columns = {
    'Year':'year',
    'Customs Score':'customs',
    'Infrastructure Score': 'infrastructure',
    'International shipments Score': 'international_shipments',
    'Logistics competence Score': 'logistics_competence',
    'Tracking & tracing Score': 'tracking',
    'Timeliness Score': 'timeliness'
}, inplace = True
)

In [ ]:
cols = df.columns.tolist()
cols.remove('country_code')
df = df[['country_code'] + cols]
display(df.head())

,country_code,year,customs,infrastructure,international_shipments,logistics_competence,tracking,timeliness
0,AUS,2023,3.7,4.1,3.1,3.9,4.1,3.6
1,BEL,2023,3.9,4.1,3.8,4.2,4.0,4.2
2,BRA,2023,2.9,3.2,2.9,3.3,3.2,3.5
3,CAN,2023,4.0,4.3,3.6,4.2,4.1,4.1
4,CHN,2023,3.3,4.0,3.6,3.8,3.8,3.7

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   country_code             21 non-null     object
 1   year                     21 non-null     int64
 2   customs                  21 non-null     float64
 3   infrastructure           21 non-null     float64
 4   international_shipments  21 non-null     float64
 5   logistics_competence     21 non-null     float64
 6   tracking                 21 non-null     float64
 7   timeliness               21 non-null     float64
dtypes: float64(6), int64(1), object(1)
memory usage: 1.4+ KB

In [ ]:
df.to_csv('International_LPI_Scorecard_Select_Countries.csv', index=False)

In [ ]:
df = pd.read_csv('/content/International_LPI_Scorecard_Select_Countries.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   country_code             21 non-null     object
 1   year                     21 non-null     int64
 2   customs                  21 non-null     float64
 3   infrastructure           21 non-null     float64
 4   international_shipments  21 non-null     float64
 5   logistics_competence     21 non-null     float64
 6   tracking                 21 non-null     float64
 7   timeliness               21 non-null     float64
dtypes: float64(6), int64(1), object(1)
memory usage: 1.4+ KB

In [ ]:
df.country_code.unique()

array(['AUS', 'BEL', 'BRA', 'CAN', 'CHN', 'FIN', 'FRA', 'DEU', 'HKG',
       'IND', 'IDN', 'JPN', 'MYS', 'MEX', 'NLD', 'Philippines', 'SGP',
       'THA', 'ARE', 'GBR', 'USA'], dtype=object)

In [ ]:
df.drop(df.loc[lambda x: x.country_code == 'Philippines'].index, axis=0, inplace=True)

In [ ]:
df.to_csv('International_LPI_Scorecard_Select_Countries_v2.csv', index=False)

# World Governance Indicators

In [ ]:
df = pd.read_csv('/content/WGI_1996_2023.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7709 entries, 0 to 7708
Data columns (total 29 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   7706 non-null   object
 1   Country Code   7704 non-null   object
 2   Series Name    7704 non-null   object
 3   Series Code    7704 non-null   object
 4   1996 [YR1996]  7704 non-null   object
 5   1998 [YR1998]  7704 non-null   object
 6   2000 [YR2000]  7704 non-null   object
 7   2002 [YR2002]  7704 non-null   object
 8   2003 [YR2003]  7704 non-null   object
 9   2004 [YR2004]  7704 non-null   object
 10  2005 [YR2005]  7704 non-null   object
 11  2006 [YR2006]  7704 non-null   object
 12  2007 [YR2007]  7704 non-null   object
 13  2008 [YR2008]  7704 non-null   object
 14  2009 [YR2009]  7704 non-null   object
 15  2010 [YR2010]  7704 non-null   object
 16  2011 [YR2011]  7704 non-null   object
 17  2012 [YR2012]  7704 non-null   object
 18  2013 [YR2013]  7704 non-null   object
 19  2014 [YR2014]  7704 non-null   object
 20  2015 [YR2015]  7704 non-null   object
 21  2016 [YR2016]  7704 non-null   object
 22  2017 [YR2017]  7704 non-null   object
 23  2018 [YR2018]  7704 non-null   object
 24  2019 [YR2019]  7704 non-null   object
 25  2020 [YR2020]  7704 non-null   object
 26  2021 [YR2021]  7704 non-null   object
 27  2022 [YR2022]  7704 non-null   object
 28  2023 [YR2023]  7704 non-null   object
dtypes: object(29)
memory usage: 1.7+ MB

In [ ]:
df.head()

,Country Name,Country Code,Series Name,Series Code,1996 [YR1996],1998 [YR1998],2000 [YR2000],2002 [YR2002],2003 [YR2003],2004 [YR2004],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Afghanistan,AFG,Control of Corruption: Estimate,CC.EST,-1.29170477390289,-1.17601227760315,-1.27172422409058,-1.25113701820374,-1.34417974948883,-1.35064733028412,...,-1.36493408679962,-1.35471308231354,-1.54022777080536,-1.53007459640503,-1.50287592411041,-1.41931009292603,-1.49336087703705,-1.15226578712463,-1.18368434906006,-1.15493178367615
1,Afghanistan,AFG,Control of Corruption: Number of Sources,CC.NO.SRC,2,2,2,2,3,5,...,11,11,10,10,10,10,9,8,8,8
2,Afghanistan,AFG,Control of Corruption: Percentile Rank,CC.PER.RNK,4.30107545852661,8.02138996124268,4.78723382949829,4.7619047164917,4.7619047164917,6.40394067764282,...,5.28846168518066,5.7142858505249,3.80952382087708,3.80952382087708,4.7619047164917,5.7142858505249,4.7619047164917,12.380952835083,12.2641506195068,13.6792449951172
3,Afghanistan,AFG,"Control of Corruption: Percentile Rank, Lower ...",CC.PER.RNK.LOWER,0,0,0,0,0,0,...,0,0.476190477609634,0,0,0,1.42857146263123,0,4.7619047164917,4.71698093414307,6.13207530975342
4,Afghanistan,AFG,"Control of Corruption: Percentile Rank, Upper ...",CC.PER.RNK.UPPER,27.4193553924561,33.6898384094238,30.8510646820068,32.8042335510254,19.0476188659668,15.2709360122681,...,12.5,12.8571424484253,10,9.5238094329834,9.5238094329834,11.9047622680664,10.4761905670166,20.9523811340332,20.2830181121826,20.7547168731689

In [ ]:
df['Series Code'].unique()

array(['CC.EST', 'CC.NO.SRC', 'CC.PER.RNK', 'CC.PER.RNK.LOWER',
       'CC.PER.RNK.UPPER', 'CC.STD.ERR', 'GE.EST', 'GE.NO.SRC',
       'GE.PER.RNK', 'GE.PER.RNK.LOWER', 'GE.PER.RNK.UPPER', 'GE.STD.ERR',
       'PV.EST', 'PV.NO.SRC', 'PV.PER.RNK', 'PV.PER.RNK.LOWER',
       'PV.PER.RNK.UPPER', 'PV.STD.ERR', 'RQ.EST', 'RQ.NO.SRC',
       'RQ.PER.RNK', 'RQ.PER.RNK.LOWER', 'RQ.PER.RNK.UPPER', 'RQ.STD.ERR',
       'RL.EST', 'RL.NO.SRC', 'RL.PER.RNK', 'RL.PER.RNK.LOWER',
       'RL.PER.RNK.UPPER', 'RL.STD.ERR', 'VA.EST', 'VA.NO.SRC',
       'VA.PER.RNK', 'VA.PER.RNK.LOWER', 'VA.PER.RNK.UPPER', 'VA.STD.ERR',
       nan], dtype=object)

In [ ]:
df_filtered = df.loc[df['Series Code'].str.contains(r'.*\.EST', na=False)]

In [ ]:
df_filtered.head()

,Country Name,Country Code,Series Name,Series Code,1996 [YR1996],1998 [YR1998],2000 [YR2000],2002 [YR2002],2003 [YR2003],2004 [YR2004],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Afghanistan,AFG,Control of Corruption: Estimate,CC.EST,-1.29170477390289,-1.17601227760315,-1.27172422409058,-1.25113701820374,-1.34417974948883,-1.35064733028412,...,-1.36493408679962,-1.35471308231354,-1.54022777080536,-1.53007459640503,-1.50287592411041,-1.41931009292603,-1.49336087703705,-1.15226578712463,-1.18368434906006,-1.15493178367615
6,Afghanistan,AFG,Government Effectiveness: Estimate,GE.EST,-2.17516660690308,-2.10229182243347,-2.17394614219666,-1.58768701553345,-1.17576801776886,-0.945146262645721,...,-1.36164617538452,-1.39739489555359,-1.29146802425385,-1.38659679889679,-1.50175786018372,-1.5191125869751,-1.61153948307037,-1.67058789730072,-1.88003480434418,-1.98701369762421
12,Afghanistan,AFG,Political Stability and Absence of Violence/Te...,PV.EST,-2.41730952262878,-2.42735457420349,-2.43896889686584,-2.03503370285034,-2.19837236404419,-2.29568219184875,...,-2.41106843948364,-2.56262516975403,-2.6621561050415,-2.7949755191803,-2.75344133377075,-2.65253973007202,-2.702721118927,-2.51867604255676,-2.54495596885681,-2.48408055305481
18,Afghanistan,AFG,Regulatory Quality: Estimate,RQ.EST,-2.09033036231995,-2.06287217140198,-2.0802526473999,-1.81154572963715,-1.46310782432556,-1.51154899597168,...,-1.12413370609283,-1.0188262462616,-1.33969509601593,-1.36301040649414,-1.13820362091064,-1.11377799510956,-1.38916301727295,-1.31168210506439,-1.27180624008179,-1.26642525196075
24,Afghanistan,AFG,Rule of Law: Estimate,RL.EST,-1.78807544708252,-1.73488676548004,-1.78066074848175,-1.67347323894501,-1.5582937002182,-1.6939252614975,...,-1.4377019405365,-1.51620066165924,-1.52253365516663,-1.58117640018463,-1.68912386894226,-1.74210047721863,-1.83140671253204,-1.87723398208618,-1.65984559059143,-1.64964091777802

In [ ]:
year_cols = [col for col in df_filtered.columns if '[YR' in col]
id_vars = [col for col in df_filtered.columns if col not in year_cols]

df_melted = pd.melt(df_filtered, id_vars=id_vars, value_vars=year_cols, var_name='year_col', value_name='value')

# Extract just the year number from the year_col and convert to integer
df_melted['year'] = df_melted['year_col'].str.extract(r'(\d{4})').astype(int)

# Convert the 'value' column to numeric, coercing errors to NaN
df_melted['value'] = pd.to_numeric(df_melted['value'], errors='coerce')

# Drop the original 'year_col' as we have the cleaned 'year' column
df_melted = df_melted.drop(columns=['year_col'])

display(df_melted.head())

,Country Name,Country Code,Series Name,Series Code,value,year
0,Afghanistan,AFG,Control of Corruption: Estimate,CC.EST,-1.291705,1996
1,Afghanistan,AFG,Government Effectiveness: Estimate,GE.EST,-2.175167,1996
2,Afghanistan,AFG,Political Stability and Absence of Violence/Te...,PV.EST,-2.417310,1996
3,Afghanistan,AFG,Regulatory Quality: Estimate,RQ.EST,-2.090330,1996
4,Afghanistan,AFG,Rule of Law: Estimate,RL.EST,-1.788075,1996

In [ ]:
df_melted['Series Name'].unique()

array(['Control of Corruption: Estimate',
       'Government Effectiveness: Estimate',
       'Political Stability and Absence of Violence/Terrorism: Estimate',
       'Regulatory Quality: Estimate', 'Rule of Law: Estimate',
       'Voice and Accountability: Estimate'], dtype=object)

In [ ]:
df_melted['Series Name'] = df_melted['Series Name'].apply(lambda x: x.split(':')[0].strip().lower().replace(' ', '_'))
display(df_melted.head())

,Country Name,Country Code,Series Name,Series Code,value,year
0,Afghanistan,AFG,control_of_corruption,CC.EST,-1.291705,1996
1,Afghanistan,AFG,government_effectiveness,GE.EST,-2.175167,1996
2,Afghanistan,AFG,political_stability_and_absence_of_violence/te...,PV.EST,-2.417310,1996
3,Afghanistan,AFG,regulatory_quality,RQ.EST,-2.090330,1996
4,Afghanistan,AFG,rule_of_law,RL.EST,-1.788075,1996

In [ ]:
df_melted = df_melted.loc[lambda x: x.year == 2023].reset_index().drop(columns = ['Series Code','index'])

In [ ]:
df_melted

,Country Name,Country Code,Series Name,value,year
0,Afghanistan,AFG,control_of_corruption,-1.154932,2023
1,Afghanistan,AFG,government_effectiveness,-1.987014,2023
2,Afghanistan,AFG,political_stability_and_absence_of_violence/te...,-2.484081,2023
3,Afghanistan,AFG,regulatory_quality,-1.266425,2023
4,Afghanistan,AFG,rule_of_law,-1.649641,2023
...,...,...,...,...,...
1279,Zimbabwe,ZWE,government_effectiveness,-1.170335,2023
1280,Zimbabwe,ZWE,political_stability_and_absence_of_violence/te...,-0.934447,2023
1281,Zimbabwe,ZWE,regulatory_quality,-1.338359,2023
1282,Zimbabwe,ZWE,rule_of_law,-1.277143,2023
1283,Zimbabwe,ZWE,voice_and_accountability,-1.092633,2023

In [ ]:
df_melted = df_melted.loc[lambda x: x['Country Code'].isin(mapping.values())]

In [ ]:
df_melted.head()

,Country Name,Country Code,Series Name,value,year
66,Australia,AUS,control_of_corruption,1.781205,2023
67,Australia,AUS,government_effectiveness,1.589880,2023
68,Australia,AUS,political_stability_and_absence_of_violence/te...,0.917057,2023
69,Australia,AUS,regulatory_quality,1.942206,2023
70,Australia,AUS,rule_of_law,1.523184,2023

In [ ]:
df_pivot = df_melted.pivot_table(index=['Country Name', 'Country Code', 'year'], columns='Series Name', values='value').reset_index()

df_pivot.columns.name = None # Remove the 'Series Name' column name
display(df_pivot.head())

,Country Name,Country Code,year,control_of_corruption,government_effectiveness,political_stability_and_absence_of_violence/terrorism,regulatory_quality,rule_of_law,voice_and_accountability
0,Australia,AUS,2023,1.781205,1.589880,0.917057,1.942206,1.523184,1.506602
1,Belgium,BEL,2023,1.336844,1.037022,0.403853,1.168225,1.295375,1.325729
2,Brazil,BRA,2023,-0.503643,-0.546764,-0.408568,-0.296478,-0.308803,0.382854
3,Canada,CAN,2023,1.671501,1.516803,0.822421,1.644710,1.473006,1.479646
4,China,CHN,2023,-0.005370,0.679014,-0.513097,-0.356508,-0.040130,-1.504554

In [ ]:
df_pivot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Country Name                                           20 non-null     object
 1   Country Code                                           20 non-null     object
 2   year                                                   20 non-null     int64
 3   control_of_corruption                                  20 non-null     float64
 4   government_effectiveness                               20 non-null     float64
 5   political_stability_and_absence_of_violence/terrorism  20 non-null     float64
 6   regulatory_quality                                     20 non-null     float64
 7   rule_of_law                                            20 non-null     float64
 8   voice_and_accountability                               20 non-null     float64
dtypes: float64(6), int64(1), object(2)
memory usage: 1.5+ KB

In [ ]:
df_pivot.rename(columns = {'Country Code': 'country_code'}).drop('Country Name', axis=1).to_csv('WGI_Select_Countries.csv', index=False)

# UN Trade & Development (US Port Calls)

In [ ]:
df = pd.read_csv('/content/US_PortCalls.csv')

In [ ]:
df.head()

,Year,Economy,Economy Label,CommercialMarket,CommercialMarket Label,Median time in port (days),Median time in port (days) Footnote,Median time in port (days) Missing value,Average age of vessels (years),Average age of vessels (years) Footnote,...,Average container carrying capacity (TEU) per container ship Missing value,Maximum size (GT) of vessels,Maximum size (GT) of vessels Footnote,Maximum size (GT) of vessels Missing value,Maximum cargo carrying capacity (dwt) of vessels,Maximum cargo carrying capacity (dwt) of vessels Footnote,Maximum cargo carrying capacity (dwt) of vessels Missing value,Maximum container carrying capacity (TEU) of container ships,Maximum container carrying capacity (TEU) of container ships Footnote,Maximum container carrying capacity (TEU) of container ships Missing value
0,2018,0,World,0,All ships,0.97,NaN,NaN,18.0,NaN,...,NaN,234006.0,NaN,NaN,441561.0,NaN,NaN,21413.0,NaN,NaN
1,2018,0,World,2,Liquid bulk carriers,0.94,NaN,NaN,13.0,NaN,...,Not available or not separately reported,234006.0,NaN,NaN,441561.0,NaN,NaN,NaN,NaN,Not available or not separately reported
2,2018,0,World,7,Liquefied petroleum gas carriers,1.02,NaN,NaN,14.0,NaN,...,Not available or not separately reported,58100.0,NaN,NaN,64220.0,NaN,NaN,NaN,NaN,Not available or not separately reported
3,2018,0,World,8,Liquefied natural gas carriers,1.11,NaN,NaN,10.0,NaN,...,Not available or not separately reported,168189.0,NaN,NaN,155159.0,NaN,NaN,NaN,NaN,Not available or not separately reported
4,2018,0,World,5,Dry bulk carriers,2.05,NaN,NaN,13.0,NaN,...,Not available or not separately reported,203483.0,NaN,NaN,404389.0,NaN,NaN,NaN,NaN,Not available or not separately reported

In [ ]:
df = df.loc[lambda x: x.Year == 2023].loc[lambda x: x['Economy Label'].isin(mapping.keys())]

In [ ]:
df['country_code'] = df['Economy Label'].replace(mapping)

In [ ]:
df = df.rename(columns = {'Year':'year'})

In [ ]:
df['CommercialMarket Label'].unique()

array(['All ships', 'Liquid bulk carriers',
       'Liquefied petroleum gas carriers',
       'Liquefied natural gas carriers', 'Dry bulk carriers',
       'Dry breakbulk carriers', 'Roll-on/ roll-off ships',
       'Container ships', 'Passenger ships'], dtype=object)

In [ ]:
df = df.loc[lambda x: x['CommercialMarket Label'] == 'Container ships']

In [ ]:
df.head()

,year,Economy,Economy Label,CommercialMarket,CommercialMarket Label,Median time in port (days),Median time in port (days) Footnote,Median time in port (days) Missing value,Average age of vessels (years),Average age of vessels (years) Footnote,...,Maximum size (GT) of vessels,Maximum size (GT) of vessels Footnote,Maximum size (GT) of vessels Missing value,Maximum cargo carrying capacity (dwt) of vessels,Maximum cargo carrying capacity (dwt) of vessels Footnote,Maximum cargo carrying capacity (dwt) of vessels Missing value,Maximum container carrying capacity (TEU) of container ships,Maximum container carrying capacity (TEU) of container ships Footnote,Maximum container carrying capacity (TEU) of container ships Missing value,country_code
1012,2023,36,Australia,3,Container ships,1.4417,NaN,NaN,15.0,NaN,...,111249.0,NaN,NaN,NaN,NaN,Not available or not separately reported,9661.0,NaN,NaN,AUS
1020,2023,124,Canada,3,Container ships,1.4569,NaN,NaN,15.0,NaN,...,176546.0,NaN,NaN,NaN,NaN,Not available or not separately reported,16000.0,NaN,NaN,CAN
1029,2023,156,China,3,Container ships,0.6049,NaN,NaN,13.0,NaN,...,237000.0,NaN,NaN,NaN,NaN,Not available or not separately reported,24116.0,NaN,NaN,CHN
1053,2023,251,France,3,Container ships,0.8535,NaN,NaN,14.0,NaN,...,236583.0,NaN,NaN,NaN,NaN,Not available or not separately reported,24116.0,NaN,NaN,FRA
1062,2023,276,Germany,3,Container ships,1.0174,NaN,NaN,15.0,NaN,...,237000.0,NaN,NaN,NaN,NaN,Not available or not separately reported,24004.0,NaN,NaN,DEU

In [ ]:
df.rename(columns = {'Median time in port (days)': 'median_days_in_port'}, inplace=True)

In [ ]:
df = df[['country_code', 'year', 'median_days_in_port']].reset_index().drop('index', axis=1)

In [ ]:
df.head()

  country_code  year  median_days_in_port
0          AUS  2023               1.4417
1          CAN  2023               1.4569
2          CHN  2023               0.6049
3          FRA  2023               0.8535
4          DEU  2023               1.0174

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country_code         9 non-null      object
 1   year                 9 non-null      int64
 2   median_days_in_port  9 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 348.0+ bytes

In [ ]:
df.country_code.unique()

array(['AUS', 'CAN', 'CHN', 'FRA', 'DEU', 'IDN', 'JPN', 'SGP', 'GBR'],
      dtype=object)

In [ ]:
df.to_csv('US_PortCalls_Time_for_ContainerShips_2023_Select_Countries.csv', index=False)

## Tarrifs

In [ ]:
df = pd.read_excel('/content/tariff_database_2025.xlsx')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13100 entries, 0 to 13099
Columns: 122 entries, hts8 to usmca_other_rate
dtypes: datetime64[ns](2), float64(76), int64(1), object(43)
memory usage: 12.2+ MB

In [ ]:
df.head()

,hts8,brief_description,quantity_1_code,quantity_2_code,wto_binding_code,mfn_text_rate,mfn_rate_type_code,mfn_ave,mfn_ad_val_rate,mfn_specific_rate,...,japan_indicator,japan_rate_type_code,japan_ad_val_rate,japan_specific_rate,japan_other_rate,usmca_indicator,usmca_rate_type_code,usmca_ad_val_rate,usmca_specific_rate,usmca_other_rate
0,1012100,Live purebred breeding horses,NO,NaN,B,Free,0,NaN,0.000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1012900,Live horses other than purebred breeding horses,NO,NaN,B,Free,0,NaN,0.000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1013000,Live asses,NO,NaN,B,6.8%,7,NaN,0.068,0.0,...,NaN,NaN,NaN,NaN,NaN,S,0.0,0.0,0.0,0.0
3,1019030,Mules and hinnies imported for immediate slaug...,NO,NaN,B,Free,0,NaN,0.000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1019040,Mules and hinnies not imported for immediate s...,NO,NaN,B,4.5%,7,NaN,0.045,0.0,...,NaN,NaN,NaN,NaN,NaN,S,0.0,0.0,0.0,0.0

In [ ]:
df['hts8'] = df['hts8'].astype(str)

valid_chapters = ('84', '85', '90')

mask_chapter = df['hts8'].str.startswith(valid_chapters)

df_elec = df[mask_chapter].copy()

In [ ]:
include_keywords = [
    "semiconductor", "integrated circuit", "IC", "microprocessor", "microcontroller",
    "logic", "memory", "flash", "DRAM", "SRAM", "EPROM", "EEPROM", "MPU", "MCU",
    "diode", "transistor", "thyristor", "LED", "capacitor", "resistor", "inductor",
    "transformer", "connector", "relay", "sensor", "oscillator", "crystal",
    "printed circuit", "PCB", "circuit assembly", "electronic component"
]

exclude_keywords = [
    "television", "smartphone", "washing machine", "refrigerator", "camera",
    "microwave", "printer", "monitor", "projector", "radio", "speaker", "headphone"
]

mask_include = df_elec['brief_description'].str.contains('|'.join(include_keywords), case=False, na=False)
mask_exclude = df_elec['brief_description'].str.contains('|'.join(exclude_keywords), case=False, na=False)

df_filtered = df_elec[mask_include & ~mask_exclude]

In [ ]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6014 entries, 16 to 13094
Columns: 122 entries, hts8 to usmca_other_rate
dtypes: datetime64[ns](2), float64(76), int64(1), object(43)
memory usage: 5.6+ MB

In [ ]:
df_filtered.shape

(916, 122)

In [ ]:
df_filtered.head()

,hts8,brief_description,quantity_1_code,quantity_2_code,wto_binding_code,mfn_text_rate,mfn_rate_type_code,mfn_ave,mfn_ad_val_rate,mfn_specific_rate,...,japan_indicator,japan_rate_type_code,japan_ad_val_rate,japan_specific_rate,japan_other_rate,usmca_indicator,usmca_rate_type_code,usmca_ad_val_rate,usmca_specific_rate,usmca_other_rate
1080,9042160,"Fruits of the genus Capsicum, other than papri...",KG,NaN,B,2.5 cents/kg,1,NaN,0.0,0.025,...,NaN,NaN,NaN,NaN,NaN,S,0.0,0.0,0.0,0.0
1081,9042180,Fruits of the genus Pimenta (including allspic...,KG,NaN,B,Free,0,NaN,0.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1085,9042276,"Fruits of the genus capsicum, crushed or groun...",KG,NaN,B,5 cents/kg,1,NaN,0.0,0.050,...,NaN,NaN,NaN,NaN,NaN,S,0.0,0.0,0.0,0.0
1086,9042280,Fruits of the genus Pimenta (including allspic...,KG,NaN,B,Free,0,NaN,0.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1089,9061100,Cinnamon (Cinnamomum zeylanicum Blume) neithe...,KG,NaN,B,Free,0,NaN,0.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
include_keywords = [
    r"\bsemiconductor(s)?\b",
    r"\bintegrated circuit(s)?\b",
    r"\bmicroprocessor(s)?\b",
    r"\bmicrocontroller(s)?\b",
    r"\bdiode(s)?\b",
    r"\btransistor(s)?\b",
    r"\bthyristor(s)?\b",
    r"\bLED(s)?\b",
    r"\bcapacitor(s)?\b",
    r"\bresistor(s)?\b",
    r"\binductor(s)?\b",
    r"\btransformer(s)?\b",
    r"\bconnector(s)?\b",
    r"\brelay(s)?\b",
    r"\bsensor(s)?\b",
    r"\boscillator(s)?\b",
    r"\bcrystal(s)?\b",
    r"\bprinted circuit\b",
    r"\bPCB(s)?\b",
    r"\bcircuit assembly\b",
    r"\belectronic component(s)?\b"
]

exclude_keywords = [
    r"\btelevision(s)?\b",
    r"\bsmartphone(s)?\b",
    r"\bwashing machine(s)?\b",
    r"\brefrigerator(s)?\b",
    r"\bcamera(s)?\b",
    r"\bmicrowave(s)?\b",
    r"\bprinter(s)?\b",
    r"\bmonitor(s)?\b",
    r"\bprojector(s)?\b",
    r"\bradio(s)?\b",
    r"\bspeaker(s)?\b",
    r"\bheadphone(s)?\b"
]

inc_pattern = "|".join(include_keywords)
exc_pattern = "|".join(exclude_keywords)

mask_include = df_elec['brief_description'].str.contains(inc_pattern, case=False, na=False, regex=True)
mask_exclude = df_elec['brief_description'].str.contains(exc_pattern, case=False, na=False, regex=True)

df_filtered = df_elec[mask_include & ~mask_exclude].copy()

/tmp/ipython-input-3854376762.py:43: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask_include = df_elec['brief_description'].str.contains(inc_pattern, case=False, na=False, regex=True)
/tmp/ipython-input-3854376762.py:44: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask_exclude = df_elec['brief_description'].str.contains(exc_pattern, case=False, na=False, regex=True)

In [ ]:
df_filtered.head()

,hts8,brief_description,quantity_1_code,quantity_2_code,wto_binding_code,mfn_text_rate,mfn_rate_type_code,mfn_ave,mfn_ad_val_rate,mfn_specific_rate,...,japan_indicator,japan_rate_type_code,japan_ad_val_rate,japan_specific_rate,japan_other_rate,usmca_indicator,usmca_rate_type_code,usmca_ad_val_rate,usmca_specific_rate,usmca_other_rate
8892,84145915,"Fans used for cooling microprocessors, telecom...",NO,NaN,B,Free,0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9015,84248910,"Mechanical appliances for projecting, dispersi...",NO,NaN,B,Free,0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9446,84733011,"Printed circuit assemblies, not incorporating ...",NaN,NaN,B,Free,0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9447,84733020,Parts and accessories of the ADP machines of h...,NO,NaN,B,Free,0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9450,84734010,Printed circuit assemblies for automatic telle...,NO,NaN,B,Free,0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
exclude_keywords_extra = [ r"\bwaste\b", r"\boil(s)?\b", r"\bPCB(s)?\b", # chemical PCBs, not printed circuit boards
                          r"\bPCT(s)?\b", r"\bPBB(s)?\b", r"\bpolychlorinated\b", r"\bhalogenated\b" ]

In [ ]:
exclude_keywords_all = exclude_keywords + exclude_keywords_extra

exc_pattern = "|".join(exclude_keywords_all)

mask_exclude = df_elec['brief_description'].str.contains(exc_pattern, case=False, na=False, regex=True)

df_filtered2 = df_elec[mask_include & ~mask_exclude]

/tmp/ipython-input-4280013194.py:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask_exclude = df_elec['brief_description'].str.contains(exc_pattern, case=False, na=False, regex=True)

In [ ]:
df_filtered2.head()

,hts8,brief_description,quantity_1_code,quantity_2_code,wto_binding_code,mfn_text_rate,mfn_rate_type_code,mfn_ave,mfn_ad_val_rate,mfn_specific_rate,...,japan_indicator,japan_rate_type_code,japan_ad_val_rate,japan_specific_rate,japan_other_rate,usmca_indicator,usmca_rate_type_code,usmca_ad_val_rate,usmca_specific_rate,usmca_other_rate
8892,84145915,"Fans used for cooling microprocessors, telecom...",NO,NaN,B,Free,0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9015,84248910,"Mechanical appliances for projecting, dispersi...",NO,NaN,B,Free,0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9446,84733011,"Printed circuit assemblies, not incorporating ...",NaN,NaN,B,Free,0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9447,84733020,Parts and accessories of the ADP machines of h...,NO,NaN,B,Free,0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9450,84734010,Printed circuit assemblies for automatic telle...,NO,NaN,B,Free,0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
keep_cols = [
    'hts8',
    'brief_description',
    'mfn_text_rate',
    'usmca_other_rate',
    'wto_binding_code',
    'quantity_1_code',
    'quantity_2_code'
]

df_final = df_filtered2[keep_cols].copy()

In [ ]:
df_final.info() # uscma_other_rate can have nulls because rate only applies to Mexico and Canada

<class 'pandas.core.frame.DataFrame'>
Index: 142 entries, 8892 to 10822
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   hts8               142 non-null    object
 1   brief_description  142 non-null    object
 2   mfn_text_rate      142 non-null    object
 3   usmca_other_rate   27 non-null     float64
 4   wto_binding_code   142 non-null    object
 5   quantity_1_code    141 non-null    object
 6   quantity_2_code    0 non-null      object
dtypes: float64(1), object(6)
memory usage: 8.9+ KB

In [ ]:
df_final.drop(columns = 'quantity_2_code', axis=1, inplace=True)

In [ ]:
df_final.reset_index().drop('index', axis=1, inplace=True)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 142 entries, 8892 to 10822
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   hts8               142 non-null    object
 1   brief_description  142 non-null    object
 2   mfn_text_rate      142 non-null    object
 3   usmca_other_rate   27 non-null     float64
 4   wto_binding_code   142 non-null    object
 5   quantity_1_code    141 non-null    object
dtypes: float64(1), object(5)
memory usage: 7.8+ KB

In [ ]:
# the one unit is the correct way to interpret 'unit not applicable' for that row above

In [ ]:
df_final.to_csv('tarriff_database_2025_only_semiconductor_components.csv', index=False)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/tarriff_database_2025_only_semiconductor_components.csv')

In [ ]:
df.head()

,hts8,brief_description,mfn_text_rate,usmca_other_rate,wto_binding_code,quantity_1_code
0,84145915,"Fans used for cooling microprocessors, telecom...",Free,NaN,B,NO
1,84248910,"Mechanical appliances for projecting, dispersi...",Free,NaN,B,NO
2,84733011,"Printed circuit assemblies, not incorporating ...",Free,NaN,B,NaN
3,84733020,Parts and accessories of the ADP machines of h...,Free,NaN,B,NO
4,84734010,Printed circuit assemblies for automatic telle...,Free,NaN,B,NO

In [ ]:
df.mfn_text_rate.unique()

array(['Free', '3.1%', '3.9%', '1.6%', '6.6%', '2.4%', '2.5%', '1.3%',
       '4.5%', '2.7%', '3.5%', '2%', '2.6%', '5.3%', '3.7%', '3.2%'],
      dtype=object)

In [ ]:
df['mfn_text_rate'] = (df['mfn_text_rate']
                             .str.replace('Free', '0.0', regex=False)
                             .str.replace('%', '', regex=False)
                             .astype(float)
                            )


print(df.mfn_text_rate.unique())

df.info()

[0.  3.1 3.9 1.6 6.6 2.4 2.5 1.3 4.5 2.7 3.5 2.  2.6 5.3 3.7 3.2]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   hts8               142 non-null    int64
 1   brief_description  142 non-null    object
 2   mfn_text_rate      142 non-null    float64
 3   usmca_other_rate   27 non-null     float64
 4   wto_binding_code   142 non-null    object
 5   quantity_1_code    141 non-null    object
dtypes: float64(2), int64(1), object(3)
memory usage: 6.8+ KB

In [ ]:
df.rename(columns={'mfn_text_rate':'mfn_text_rate_pct'}, inplace=True)

In [ ]:
df.usmca_other_rate.unique()

array([nan,  0.])

In [ ]:
df.wto_binding_code.unique()

array(['B'], dtype=object)

In [ ]:
df.quantity_1_code.unique()

array(['NO', nan, 'KG'], dtype=object)

In [ ]:
df.quantity_1_code.value_counts(dropna=False, normalize=True)

quantity_1_code
NO     0.915493
KG     0.077465
NaN    0.007042
Name: proportion, dtype: float64

In [ ]:
df.rename({'quantity_1_code':'how_measured'}, axis=1, inplace=True)

In [ ]:
df.drop(['usmca_other_rate', 'wto_binding_code'], axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   hts8               142 non-null    int64
 1   brief_description  142 non-null    object
 2   mfn_text_rate_pct  142 non-null    float64
 3   how_measured       141 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 4.6+ KB

In [ ]:
df.to_csv('tarriff_database_2025_only_semiconductor_components_v2.csv', index=False)

# Producer Price Indexes

## BLS Integrated Circuit Components

In [ ]:
df = pd.read_excel('/content/Integrated Circuit Packages.xlsx', header=10)

In [ ]:
df.drop(0, axis=0, inplace = True)

In [ ]:
df.head()

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
1,1976,357.3,355.3,349.9,351.5,351.9,352.1,351.7,342.0,336.0,332.4,331.0,323.4
2,1977,322.1,318.7,314.9,310.2,307.8,304.6,303.1,301.7,300.3,298.4,296.6,278.5
3,1978,276.0,274.0,272.9,256.0,255.8,255.8,248.4,247.1,246.3,246.0,246.0,246.0
4,1979,243.0,242.6,243.1,244.1,243.5,243.3,239.9,239.6,240.3,240.6,245.8,250.0
5,1980,251.0,257.0,261.0,265.1,268.7,269.6,268.7,265.4,265.5,261.8,256.6,259.7

In [ ]:
month_columns = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
df_melted = df.melt(id_vars=['Year'], value_vars=month_columns, var_name='month_name', value_name='price')

month_mapping = {
    'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
    'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12
}
df_melted['month'] = df_melted['month_name'].map(month_mapping)

df_melted.sort_values(by=['Year', 'month'], inplace=True)
df_melted.reset_index(drop=True, inplace=True)
display(df_melted.head())

   Year month_name  price  month
0  1976        Jan  357.3      1
1  1976        Feb  355.3      2
2  1976        Mar  349.9      3
3  1976        Apr  351.5      4
4  1976        May  351.9      5

In [ ]:
df_melted.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        600 non-null    int64
 1   month_name  600 non-null    object
 2   price       571 non-null    float64
 3   month       600 non-null    int64
dtypes: float64(1), int64(2), object(1)
memory usage: 18.9+ KB

In [ ]:
df_melted.loc[lambda x: x.price.isna()]

     Year month_name  price  month
65   1981        Jun    NaN      6
408  2010        Jan    NaN      1
409  2010        Feb    NaN      2
410  2010        Mar    NaN      3
411  2010        Apr    NaN      4
476  2015        Sep    NaN      9
477  2015        Oct    NaN     10
478  2015        Nov    NaN     11
479  2015        Dec    NaN     12
480  2016        Jan    NaN      1
481  2016        Feb    NaN      2
482  2016        Mar    NaN      3
581  2024        Jun    NaN      6
582  2024        Jul    NaN      7
583  2024        Aug    NaN      8
584  2024        Sep    NaN      9
585  2024        Oct    NaN     10
586  2024        Nov    NaN     11
587  2024        Dec    NaN     12
588  2025        Jan    NaN      1
589  2025        Feb    NaN      2
590  2025        Mar    NaN      3
591  2025        Apr    NaN      4
592  2025        May    NaN      5
593  2025        Jun    NaN      6
594  2025        Jul    NaN      7
597  2025        Oct    NaN     10
598  2025        Nov    NaN     11
599  2025        Dec    NaN     12

In [ ]:
df_melted = df_melted.drop(df_melted.loc[lambda x: (x.Year == 2025) | (x.Year == 2024)].index, axis=0)

In [ ]:
df_melted.tail()

     Year month_name   price  month
571  2023        Aug  21.858      8
572  2023        Sep  21.818      9
573  2023        Oct  21.635     10
574  2023        Nov  21.757     11
575  2023        Dec  21.582     12

In [ ]:
df_melted.loc[lambda x: x.price.isna()]

     Year month_name  price  month
65   1981        Jun    NaN      6
408  2010        Jan    NaN      1
409  2010        Feb    NaN      2
410  2010        Mar    NaN      3
411  2010        Apr    NaN      4
476  2015        Sep    NaN      9
477  2015        Oct    NaN     10
478  2015        Nov    NaN     11
479  2015        Dec    NaN     12
480  2016        Jan    NaN      1
481  2016        Feb    NaN      2
482  2016        Mar    NaN      3

In [ ]:
df_melted.price = df_melted.price.interpolate(method='linear') # forms a 'bridge line' between the previous price and missing. not much fluctuation in PPI month to month

In [ ]:
df_melted.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576 entries, 0 to 575
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        576 non-null    int64
 1   month_name  576 non-null    object
 2   price       576 non-null    float64
 3   month       576 non-null    int64
dtypes: float64(1), int64(2), object(1)
memory usage: 18.1+ KB

In [ ]:
df_melted.rename(columns={'Year':'year'}, inplace=True)

In [ ]:
df_melted.head()

   year month_name  price  month
0  1976        Jan  357.3      1
1  1976        Feb  355.3      2
2  1976        Mar  349.9      3
3  1976        Apr  351.5      4
4  1976        May  351.9      5

In [ ]:
df_melted = df_melted.assign(
    date = lambda x: pd.to_datetime(x.year.astype(str) + '-' + x.month.astype(str))
)

In [ ]:
df_melted = df_melted.assign(
    series_id = 'PCU3344133344131',
    industry = 'Semiconductor and related device manufacturing',
    product = 'Integrated circuit packages'
).sort_values(by='date').reset_index(drop=True)

In [ ]:
df_melted.rename(columns={'price':'ppi_value'}, inplace = True)

In [ ]:
df_melted = df_melted[['date','year','month','ppi_value', 'series_id','industry','product']]

In [ ]:
df_melted.tail()

,date,year,month,ppi_value,series_id,industry,product
571,2023-08-01,2023,8,21.858,PCU3344133344131,Semiconductor and related device manufacturing,Integrated circuit packages
572,2023-09-01,2023,9,21.818,PCU3344133344131,Semiconductor and related device manufacturing,Integrated circuit packages
573,2023-10-01,2023,10,21.635,PCU3344133344131,Semiconductor and related device manufacturing,Integrated circuit packages
574,2023-11-01,2023,11,21.757,PCU3344133344131,Semiconductor and related device manufacturing,Integrated circuit packages
575,2023-12-01,2023,12,21.582,PCU3344133344131,Semiconductor and related device manufacturing,Integrated circuit packages

In [ ]:
df_melted.to_csv('bls_ppi_integrated_circuit_packages_1976_2023.csv', index=False)

In [ ]:
df = pd.read_csv('/content/bls_ppi_integrated_circuit_packages_1976_2023.csv')

In [ ]:
df.head()

,date,year,month,ppi_value,series_id,industry,product
0,1976-01-01,1976,1,357.3,PCU3344133344131,Semiconductor and related device manufacturing,Integrated circuit packages
1,1976-02-01,1976,2,355.3,PCU3344133344131,Semiconductor and related device manufacturing,Integrated circuit packages
2,1976-03-01,1976,3,349.9,PCU3344133344131,Semiconductor and related device manufacturing,Integrated circuit packages
3,1976-04-01,1976,4,351.5,PCU3344133344131,Semiconductor and related device manufacturing,Integrated circuit packages
4,1976-05-01,1976,5,351.9,PCU3344133344131,Semiconductor and related device manufacturing,Integrated circuit packages

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576 entries, 0 to 575
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       576 non-null    object
 1   year       576 non-null    int64
 2   month      576 non-null    int64
 3   ppi_value  576 non-null    float64
 4   series_id  576 non-null    object
 5   industry   576 non-null    object
 6   product    576 non-null    object
dtypes: float64(1), int64(2), object(4)
memory usage: 31.6+ KB

In [ ]:
df.ppi_value.max()

357.3

In [ ]:
df = df.assign(
    source = 'BLS',
    country_code = 'USA',

)

In [ ]:
df = df.assign(
    base_year = df.loc[lambda x: x.ppi_value == 100].year.values[0]
)

In [ ]:
df.to_csv('bls_ppi_integrated_circuit_packages_1976_2023_v2.csv', index=False)

## BLS Microprocessors and Microcontrollers

In [ ]:
df = pd.read_excel('/content/Microprocessors and Microcontrollers.xlsx', header=10)

In [ ]:
month_columns = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
df_melted = df.melt(id_vars=['Year'], value_vars=month_columns, var_name='month_name', value_name='price')

month_mapping = {
    'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
    'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12
}
df_melted['month'] = df_melted['month_name'].map(month_mapping)

df_melted.sort_values(by=['Year', 'month'], inplace=True)
df_melted.reset_index(drop=True, inplace=True)
display(df_melted.head())

   Year month_name  price  month
0  1981        Jan    NaN      1
1  1981        Feb    NaN      2
2  1981        Mar    NaN      3
3  1981        Apr    NaN      4
4  1981        May    NaN      5

In [ ]:
df_melted.drop(index=range(5), inplace=True)

In [ ]:
df_melted.tail()

     Year month_name  price  month
415  2015        Aug    NaN      8
416  2015        Sep    NaN      9
417  2015        Oct    NaN     10
418  2015        Nov    NaN     11
419  2015        Dec    NaN     12

In [ ]:
df_melted.drop(df_melted.loc[lambda x: (x.price.isna()) & (x.Year==2015)].index, axis=0, inplace=True)

In [ ]:
df_melted.price = df_melted.price.interpolate(method='linear')

In [ ]:
df_melted.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406 entries, 5 to 410
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        406 non-null    int64
 1   month_name  406 non-null    object
 2   price       406 non-null    float64
 3   month       406 non-null    int64
dtypes: float64(1), int64(2), object(1)
memory usage: 12.8+ KB

In [ ]:
df_melted = df_melted.rename(columns = {'Year':'year', 'price':'ppi_value'}).assign(
    date = lambda x: pd.to_datetime(x.year.astype(str) + '-' + x.month.astype(str)),
    series_id = 'PCU33441333441312',
    industry = 'Semiconductor and related device manufacturing',
    product = 'Microprocessors including microcontrollers'
)[[
    'date', 'year', 'month', 'ppi_value', 'series_id', 'industry', 'product'
]]

In [ ]:
df_melted.tail()

,date,year,month,ppi_value,series_id,industry,product
406,2014-11-01,2014,11,46.3,PCU33441333441312,Semiconductor and related device manufacturing,Microprocessors including microcontrollers
407,2014-12-01,2014,12,46.3,PCU33441333441312,Semiconductor and related device manufacturing,Microprocessors including microcontrollers
408,2015-01-01,2015,1,46.3,PCU33441333441312,Semiconductor and related device manufacturing,Microprocessors including microcontrollers
409,2015-02-01,2015,2,46.3,PCU33441333441312,Semiconductor and related device manufacturing,Microprocessors including microcontrollers
410,2015-03-01,2015,3,46.1,PCU33441333441312,Semiconductor and related device manufacturing,Microprocessors including microcontrollers

In [ ]:
df_melted.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406 entries, 5 to 410
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       406 non-null    datetime64[ns]
 1   year       406 non-null    int64
 2   month      406 non-null    int64
 3   ppi_value  406 non-null    float64
 4   series_id  406 non-null    object
 5   industry   406 non-null    object
 6   product    406 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 22.3+ KB

In [ ]:
df_melted.to_csv('bls_ppi_microprocessors_and_microcontrollers_1981_2015.csv', index=False)

In [ ]:
df= pd.read_csv('/content/bls_ppi_microprocessors_and_microcontrollers_1981_2015.csv')

In [ ]:
df = df.assign(
    source = 'BLS',
    country_code = 'USA'
)

In [ ]:
df = df.assign(
    base_year = df.loc[lambda x: x.ppi_value == 100].year.values[0])

In [ ]:
df.to_csv('bls_ppi_microprocessors_and_microcontrollers_1981_2015_v2.csv', index=False)

## BLS Transistors, Diodes, and lesser components

In [ ]:
df = pd.read_excel('/content/Transistors_Diodes_Lesser Components.xlsx', header=10).drop(index=0)

In [ ]:
month_columns = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
df_melted = df.melt(id_vars=['Year'], value_vars=month_columns, var_name='month_name', value_name='price')

month_mapping = {
    'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
    'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12
}
df_melted['month'] = df_melted['month_name'].map(month_mapping)

df_melted.sort_values(by=['Year', 'month'], inplace=True)
df_melted.reset_index(drop=True, inplace=True)
display(df_melted.head())

   Year month_name  price  month
0  1977        Jan  109.0      1
1  1977        Feb  109.0      2
2  1977        Mar  109.0      3
3  1977        Apr  108.1      4
4  1977        May  107.2      5

In [ ]:
df_melted.loc[lambda x: x.price.isna()]

Empty DataFrame
Columns: [Year, month_name, price, month]
Index: []

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 588 entries, 0 to 587
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        588 non-null    int64
 1   month_name  588 non-null    object
 2   price       588 non-null    float64
 3   month       588 non-null    int64
dtypes: float64(1), int64(2), object(1)
memory usage: 18.5+ KB

In [ ]:
df_melted = df_melted.rename(columns = {'Year':'year', 'price':'ppi_value'}).assign(
    date = lambda x: pd.to_datetime(x.year.astype(str) + '-' + x.month.astype(str)),
    series_id = 'PCU334413334413A',
    industry = 'Semiconductor and related device manufacturing',
    product = 'Other semiconductor devices, including transistors, diodes, and semiconductor parts such as wafers'
)[[
    'date', 'year', 'month', 'ppi_value', 'series_id', 'industry', 'product'
]]

In [ ]:
df_melted.tail()

,date,year,month,ppi_value,series_id,industry,product
583,2025-08-01,2025,8,54.808,PCU334413334413A,Semiconductor and related device manufacturing,"Other semiconductor devices, including transis..."
584,2025-09-01,2025,9,55.058,PCU334413334413A,Semiconductor and related device manufacturing,"Other semiconductor devices, including transis..."
585,2025-10-01,2025,10,55.058,PCU334413334413A,Semiconductor and related device manufacturing,"Other semiconductor devices, including transis..."
586,2025-11-01,2025,11,55.095,PCU334413334413A,Semiconductor and related device manufacturing,"Other semiconductor devices, including transis..."
587,2025-12-01,2025,12,55.108,PCU334413334413A,Semiconductor and related device manufacturing,"Other semiconductor devices, including transis..."

In [ ]:
df_melted.to_csv('bls_ppi_transistors_diodes_lesserComponents_1977_2025.csv', index=False)

In [ ]:
df = pd.read_csv('/content/bls_ppi_transistors_diodes_lesserComponents_1977_2025.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 588 entries, 0 to 587
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       588 non-null    object
 1   year       588 non-null    int64
 2   month      588 non-null    int64
 3   ppi_value  588 non-null    float64
 4   series_id  588 non-null    object
 5   industry   588 non-null    object
 6   product    588 non-null    object
dtypes: float64(1), int64(2), object(4)
memory usage: 32.3+ KB

In [ ]:
df = df.assign(
    source = 'BLS',
    country_code = 'USA'
)

In [ ]:
df = df.assign(
    base_year = df.loc[lambda x: x.ppi_value==100].year.values.max())

In [ ]:
df.to_csv('bls_ppi_transistors_diodes_lesserComponents_1977_2025_v2.csv', index=False)

## BLS Aggregated PPI of Major Semiconductor Parts

In [ ]:
df = pd.read_excel('/content/Aggregated PPI of Major Semiconductor components.xlsx', header=10)

In [ ]:
month_columns = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
df_melted = df.melt(id_vars=['Year'], value_vars=month_columns, var_name='month_name', value_name='price')

month_mapping = {
    'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
    'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12
}
df_melted['month'] = df_melted['month_name'].map(month_mapping)

df_melted.sort_values(by=['Year', 'month'], inplace=True)
df_melted.reset_index(drop=True, inplace=True)
display(df_melted.head())

   Year month_name  price  month
0  1981        Jan    NaN      1
1  1981        Feb    NaN      2
2  1981        Mar    NaN      3
3  1981        Apr    NaN      4
4  1981        May    NaN      5

In [ ]:
df_melted.loc[lambda x: x.price.isna()]

   Year month_name  price  month
0  1981        Jan    NaN      1
1  1981        Feb    NaN      2
2  1981        Mar    NaN      3
3  1981        Apr    NaN      4
4  1981        May    NaN      5

In [ ]:
df_melted.price = df_melted.price.interpolate(method='spline', order=3)

In [ ]:
df_melted.tail()

,date,year,month,ppi_value,series_id,industry,product
535,2025-08-01,2025,8,28.392,PCU334413334413P,Semiconductor and related device manufacturing,Primary products
536,2025-09-01,2025,9,28.454,PCU334413334413P,Semiconductor and related device manufacturing,Primary products
537,2025-10-01,2025,10,28.632,PCU334413334413P,Semiconductor and related device manufacturing,Primary products
538,2025-11-01,2025,11,28.639,PCU334413334413P,Semiconductor and related device manufacturing,Primary products
539,2025-12-01,2025,12,28.655,PCU334413334413P,Semiconductor and related device manufacturing,Primary products

In [ ]:
df_melted = df_melted.rename(columns = {'Year':'year', 'price':'ppi_value'}).assign(
    date = lambda x: pd.to_datetime(x.year.astype(str) + '-' + x.month.astype(str)),
    series_id = 'PCU334413334413P',
    industry = 'Semiconductor and related device manufacturing',
    product = 'Primary products'
)[[
    'date', 'year', 'month', 'ppi_value', 'series_id', 'industry', 'product'
]]

In [ ]:
df_melted.to_csv('bls_ppi_aggregated_major_semiconductor_products_1981_2025.csv', index=False)

In [ ]:
df = pd.read_csv('/content/bls_ppi_aggregated_major_semiconductor_products_1981_2025.csv')

In [ ]:
df = df.drop(df.loc[lambda x: x.ppi_value.isna()].index, axis=0).reset_index().drop('index',axis=1)

In [ ]:
df = df.assign(
    source = 'BLS',
    country_code = 'USA',
    base_year = 1998
)

In [ ]:
df.to_csv('bls_ppi_aggregated_major_semiconductor_products_1981_2025_v2.csv', index=False)

## Fred PPIs

### Mexico Computer and Electronic Manufacturing

In [ ]:
df = pd.read_csv('/content/Mexico Computer and Electronic Manufacturing.csv')

In [ ]:
df = df.assign(
    date = lambda x: pd.to_datetime(x.observation_date),
    year = lambda x: x.date.dt.year,
    month = lambda x: x.date.dt.month,
    series_id = 'COMEXZ334',
    industry = 'Computer and electronic product manufacturing',
    product = 'Computer and electronic manufacturing',
    country_code = 'MEX'

).rename(columns={'COMEXZ334': 'ppi_value'})[[
    'date', 'year', 'month', 'ppi_value', 'series_id', 'industry', 'product'
]]

/tmp/ipython-input-751704885.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date = lambda x: pd.to_datetime(x.observation_date),

In [ ]:
df.ppi_value = df.ppi_value.interpolate(method='linear')

In [ ]:
df.tail()

,date,year,month,ppi_value,series_id,industry,product
158,2025-08-01,2025,8,78.4,COMEXZ334,Computer and electronic product manufacturing,Computer and electronic manufacturing
159,2025-09-01,2025,9,78.6,COMEXZ334,Computer and electronic product manufacturing,Computer and electronic manufacturing
160,2025-10-01,2025,10,78.7,COMEXZ334,Computer and electronic product manufacturing,Computer and electronic manufacturing
161,2025-11-01,2025,11,78.8,COMEXZ334,Computer and electronic product manufacturing,Computer and electronic manufacturing
162,2025-12-01,2025,12,78.7,COMEXZ334,Computer and electronic product manufacturing,Computer and electronic manufacturing

In [ ]:
df.to_csv('fred_ppi_mexico_computer_electronic_manufacturing_2012_2025.csv', index=False)

In [ ]:
df = pd.read_csv('/content/fred_ppi_mexico_computer_electronic_manufacturing_2012_2025.csv')

In [ ]:
df = df.assign(
    source = 'FRED',
    country_code = 'MEX',
    base_year = df.loc[lambda x: x.ppi_value == 100].year.values[0]
)

In [ ]:
df.to_csv('fred_ppi_mexico_computer_electronic_manufacturing_2012_2025_v2.csv', index=False)

### Canada Computer and Electronic Manufacturing

In [ ]:
df = pd.read_csv('/content/Canada Computer and Electronic Product Manufacturing.csv')

In [ ]:
df.head()

  observation_date  COCANZ334
0           6/1/12      100.0
1           7/1/12      100.0
2           8/1/12       99.9
3           9/1/12       99.9
4          10/1/12      100.0

In [ ]:
df = df.assign(
    date = lambda x: pd.to_datetime(x.observation_date),
    year = lambda x: x.date.dt.year,
    month = lambda x: x.date.dt.month,
    series_id = 'COCANZ334',
    industry = 'Computer and electronic product manufacturing',
    product = 'Computer and electronic manufacturing',
    country_code = 'CAN'

).rename(columns={'COCANZ334': 'ppi_value'})[[
    'date', 'year', 'month', 'ppi_value', 'series_id', 'industry', 'product'
]]

/tmp/ipython-input-3442724085.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date = lambda x: pd.to_datetime(x.observation_date),

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       103 non-null    datetime64[ns]
 1   year       103 non-null    int32
 2   month      103 non-null    int32
 3   ppi_value  103 non-null    float64
 4   series_id  103 non-null    object
 5   industry   103 non-null    object
 6   product    103 non-null    object
dtypes: datetime64[ns](1), float64(1), int32(2), object(3)
memory usage: 5.0+ KB

In [ ]:
df.to_csv('fred_ppi_canada_computer_electronic_manufacturing_2012_2020.csv', index=False)

In [ ]:
df = pd.read_csv('/content/fred_ppi_canada_computer_electronic_manufacturing_2012_2020.csv')

In [ ]:
df = df.assign(
    source='FRED',
    country_code = 'CAN',
    base_year = df.loc[lambda x: x.ppi_value==100].year[0])

In [ ]:
df.to_csv('fred_ppi_canada_computer_electronic_manufacturing_2012_2020_v2.csv', index=False)

### China Semiconductor Specific

In [ ]:
df = pd.read_csv('/content/China Monthly Import Price Index.csv')

In [ ]:
df.head()

  observation_date  COCHNZ3344
0           6/1/12       100.0
1           7/1/12       101.0
2           8/1/12       101.5
3           9/1/12       101.4
4          10/1/12       101.2

In [ ]:
df = df.assign(
    date = lambda x: pd.to_datetime(x.observation_date),
    year = lambda x: x.date.dt.year,
    month = lambda x: x.date.dt.month,
    series_id = 'COCHNZ3344',
    industry = 'Semiconductor and other electronic component manufacturing',
    product = 'Semiconductor and other electronic components',
    country_code = 'CHN'

).rename(columns={'COCHNZ3344': 'ppi_value'})[[
    'date', 'year', 'month', 'ppi_value', 'series_id', 'industry', 'product'
]]

/tmp/ipython-input-1317041532.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date = lambda x: pd.to_datetime(x.observation_date),

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       79 non-null     datetime64[ns]
 1   year       79 non-null     int32
 2   month      79 non-null     int32
 3   ppi_value  79 non-null     float64
 4   series_id  79 non-null     object
 5   industry   79 non-null     object
 6   product    79 non-null     object
dtypes: datetime64[ns](1), float64(1), int32(2), object(3)
memory usage: 3.8+ KB

In [ ]:
df.to_csv('fred_ppi_china_semiconductor_manufacturing_2012_2018.csv', index=False)

In [ ]:
df = pd.read_csv('/content/fred_ppi_china_semiconductor_manufacturing_2012_2018.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       79 non-null     object
 1   year       79 non-null     int64
 2   month      79 non-null     int64
 3   ppi_value  79 non-null     float64
 4   series_id  79 non-null     object
 5   industry   79 non-null     object
 6   product    79 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 4.4+ KB

In [ ]:
df = df.assign(
    source='FRED',
    country_code='CHN',
    base_year = df.loc[lambda x: x.ppi_value==100].year.values[0])

In [ ]:
df.to_csv('fred_ppi_china_semiconductor_manufacturing_2012_2018_v2.csv', index=False)

### Other Asian Countries (Vietnam, Malaysia, Indonesia, Singapore, Thailand, Taiwan, Philippines, South Korea, etc.) Semiconductor Specific

In [ ]:
df = pd.read_csv('/content/Monthly Price Index for Other Asain Countries.csv')

In [ ]:
df.head()

,observation_date,COOASZ3344,Unnamed: 2,"Includes (aggregated for): Taiwan, South Korea, Malaysia, Singapore, Vietnam, etc."
0,6/1/12,100.0,NaN,NaN
1,7/1/12,99.2,NaN,NaN
2,8/1/12,99.1,NaN,NaN
3,9/1/12,100.0,NaN,NaN
4,10/1/12,100.1,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 4 columns):
 #   Column                                                                              Non-Null Count  Dtype
---  ------                                                                              --------------  -----
 0   observation_date                                                                    163 non-null    object
 1   COOASZ3344                                                                          162 non-null    float64
 2   Unnamed: 2                                                                          0 non-null      float64
 3   Includes (aggregated for): Taiwan, South Korea, Malaysia, Singapore, Vietnam, etc.  0 non-null      float64
dtypes: float64(3), object(1)
memory usage: 5.2+ KB

In [ ]:
df = df.assign(
    date = lambda x: pd.to_datetime(x.observation_date),
    year = lambda x: x.date.dt.year,
    month = lambda x: x.date.dt.month,
    series_id = 'COOASZ3344',
    industry = 'Semiconductor and other electronic component manufacturing',
    product = 'Semiconductor and other electronic components',
    country_code = 'OAC'

).rename(columns={'COOASZ3344': 'ppi_value'})[[
    'date', 'year', 'month', 'ppi_value', 'series_id', 'industry', 'product'
]]

/tmp/ipython-input-796156882.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date = lambda x: pd.to_datetime(x.observation_date),

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       163 non-null    datetime64[ns]
 1   year       163 non-null    int32
 2   month      163 non-null    int32
 3   ppi_value  162 non-null    float64
 4   series_id  163 non-null    object
 5   industry   163 non-null    object
 6   product    163 non-null    object
dtypes: datetime64[ns](1), float64(1), int32(2), object(3)
memory usage: 7.8+ KB

In [ ]:
df.ppi_value = df.ppi_value.interpolate(method='linear')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       163 non-null    datetime64[ns]
 1   year       163 non-null    int32
 2   month      163 non-null    int32
 3   ppi_value  163 non-null    float64
 4   series_id  163 non-null    object
 5   industry   163 non-null    object
 6   product    163 non-null    object
dtypes: datetime64[ns](1), float64(1), int32(2), object(3)
memory usage: 7.8+ KB

In [ ]:
df.tail()

,date,year,month,ppi_value,series_id,industry,product
158,2025-08-01,2025,8,95.1,COOASZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
159,2025-09-01,2025,9,95.3,COOASZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
160,2025-10-01,2025,10,96.7,COOASZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
161,2025-11-01,2025,11,98.1,COOASZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
162,2025-12-01,2025,12,98.7,COOASZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components

In [ ]:
df.to_csv('fred_ppi_other_asian_countries_semiconductor_manufacturing_2012_2025.csv', index=False)

In [ ]:
df = pd.read_csv('/content/fred_ppi_other_asian_countries_semiconductor_manufacturing_2012_2025.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       163 non-null    object
 1   year       163 non-null    int64
 2   month      163 non-null    int64
 3   ppi_value  163 non-null    float64
 4   series_id  163 non-null    object
 5   industry   163 non-null    object
 6   product    163 non-null    object
dtypes: float64(1), int64(2), object(4)
memory usage: 9.0+ KB

In [ ]:
df = df.assign(
    source='FRED',
    country_code='OAC',
    base_year = 2012
)

In [ ]:
df.to_csv('fred_ppi_other_asian_countries_semiconductor_manufacturing_2012_2025_v2.csv', index=False)

### United States Semiconductor Specific

In [ ]:
df = pd.read_csv('/content/US Monthly Import Price Index_Semiconductors_and_Electrical_Components.csv')

In [ ]:
df = df.assign(
    date = lambda x: pd.to_datetime(x.observation_date),
    year = lambda x: x.date.dt.year,
    month = lambda x: x.date.dt.month,
    series_id = 'IZ3344',
    industry = 'Semiconductor and other electronic component manufacturing',
    product = 'Semiconductor and other electronic components',
    country_code = 'USA'

).rename(columns={'IZ3344': 'ppi_value'})[[
    'date', 'year', 'month', 'ppi_value', 'series_id', 'industry', 'product'
]]

/tmp/ipython-input-193521539.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date = lambda x: pd.to_datetime(x.observation_date),

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       241 non-null    datetime64[ns]
 1   year       241 non-null    int32
 2   month      241 non-null    int32
 3   ppi_value  240 non-null    float64
 4   series_id  241 non-null    object
 5   industry   241 non-null    object
 6   product    241 non-null    object
dtypes: datetime64[ns](1), float64(1), int32(2), object(3)
memory usage: 11.4+ KB

In [ ]:
df.ppi_value = df.ppi_value.interpolate(method='linear')

In [ ]:
df.head()

,date,year,month,ppi_value,series_id,industry,product
0,2005-12-01,2005,12,100.0,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
1,2006-01-01,2006,1,99.6,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
2,2006-02-01,2006,2,99.4,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
3,2006-03-01,2006,3,99.5,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
4,2006-04-01,2006,4,98.8,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components

In [ ]:
df.tail()

,date,year,month,ppi_value,series_id,industry,product
236,2025-08-01,2025,8,77.0,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
237,2025-09-01,2025,9,77.0,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
238,2025-10-01,2025,10,77.4,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
239,2025-11-01,2025,11,77.8,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
240,2025-12-01,2025,12,77.7,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components

In [ ]:
df.to_csv('fred_ppi_united_states_semiconductor_manufacturing_2005_2025.csv', index=False)

In [ ]:
df = pd.read_csv('/content/fred_ppi_united_states_semiconductor_manufacturing_2005_2025.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       241 non-null    object
 1   year       241 non-null    int64
 2   month      241 non-null    int64
 3   ppi_value  241 non-null    float64
 4   series_id  241 non-null    object
 5   industry   241 non-null    object
 6   product    241 non-null    object
dtypes: float64(1), int64(2), object(4)
memory usage: 13.3+ KB

In [ ]:
df.head()

,date,year,month,ppi_value,series_id,industry,product
0,2005-12-01,2005,12,100.0,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
1,2006-01-01,2006,1,99.6,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
2,2006-02-01,2006,2,99.4,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
3,2006-03-01,2006,3,99.5,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components
4,2006-04-01,2006,4,98.8,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components

In [ ]:
df = df.assign(
    source='FRED',
    country_code='USA',
    base_year = 2005
)

In [ ]:
df.to_csv('fred_ppi_united_states_semiconductor_manufacturing_2005_2025_v2.csv', index=False)

## Combining all BLS + FRED data

In [ ]:
df1 = pd.read_csv('/content/bls_ppi_aggregated_major_semiconductor_products_1981_2025_v2.csv')

In [ ]:
df2 = pd.read_csv('/content/bls_ppi_integrated_circuit_packages_1976_2023_v2.csv')

In [ ]:
df3 = pd.read_csv('/content/bls_ppi_microprocessors_and_microcontrollers_1981_2015_v2.csv')

In [ ]:
df4 = pd.read_csv('/content/bls_ppi_transistors_diodes_lesserComponents_1977_2025_v2.csv')

In [ ]:
df5 = pd.read_csv('/content/fred_ppi_canada_computer_electronic_manufacturing_2012_2020_v2.csv')

In [ ]:
df6 = pd.read_csv('/content/fred_ppi_china_semiconductor_manufacturing_2012_2018_v2.csv')

In [ ]:
df7 = pd.read_csv('/content/fred_ppi_mexico_computer_electronic_manufacturing_2012_2025_v2.csv')

In [ ]:
df8 = pd.read_csv('/content/fred_ppi_other_asian_countries_semiconductor_manufacturing_2012_2025_v2.csv')

In [ ]:
df9 = pd.read_csv('/content/fred_ppi_united_states_semiconductor_manufacturing_2005_2025_v2.csv')

In [ ]:
all_ppi_dfs = [
    df1, df2, df3, df4, df5, df6, df7, df8, df9
]

df_combined_ppi = pd.concat(all_ppi_dfs, ignore_index=True)

display(df_combined_ppi.head())
display(df_combined_ppi.tail())
df_combined_ppi.info()

,date,year,month,ppi_value,series_id,industry,product,source,country_code,base_year
0,1981-06-01,1981,6,181.0,PCU334413334413P,Semiconductor and related device manufacturing,Primary products,BLS,USA,1998
1,1981-07-01,1981,7,180.5,PCU334413334413P,Semiconductor and related device manufacturing,Primary products,BLS,USA,1998
2,1981-08-01,1981,8,180.8,PCU334413334413P,Semiconductor and related device manufacturing,Primary products,BLS,USA,1998
3,1981-09-01,1981,9,179.5,PCU334413334413P,Semiconductor and related device manufacturing,Primary products,BLS,USA,1998
4,1981-10-01,1981,10,180.0,PCU334413334413P,Semiconductor and related device manufacturing,Primary products,BLS,USA,1998

,date,year,month,ppi_value,series_id,industry,product,source,country_code,base_year
2849,2025-08-01,2025,8,77.0,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components,FRED,USA,2005
2850,2025-09-01,2025,9,77.0,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components,FRED,USA,2005
2851,2025-10-01,2025,10,77.4,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components,FRED,USA,2005
2852,2025-11-01,2025,11,77.8,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components,FRED,USA,2005
2853,2025-12-01,2025,12,77.7,IZ3344,Semiconductor and other electronic component m...,Semiconductor and other electronic components,FRED,USA,2005

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2854 entries, 0 to 2853
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          2854 non-null   object
 1   year          2854 non-null   int64
 2   month         2854 non-null   int64
 3   ppi_value     2854 non-null   float64
 4   series_id     2854 non-null   object
 5   industry      2854 non-null   object
 6   product       2854 non-null   object
 7   source        2854 non-null   object
 8   country_code  2854 non-null   object
 9   base_year     2854 non-null   int64
dtypes: float64(1), int64(3), object(6)
memory usage: 223.1+ KB

In [ ]:
df_combined_ppi.to_csv('combined_ppi_data.csv', index=False)

# World Bank Commodity Prices

## Monthly

In [ ]:
df = pd.read_excel('/content/Monthly-2.xlsx', sheet_name='Monthly Prices', header=4)

In [ ]:
df.head()

,Unnamed: 0,"Crude oil, average","Crude oil, Brent","Crude oil, Dubai","Crude oil, WTI","Coal, Australian","Coal, South African **","Natural gas, US","Natural gas, Europe","Liquefied natural gas, Japan",...,Aluminum,"Iron ore, cfr spot",Copper,Lead,Tin,Nickel,Zinc,Gold,Platinum,Silver
0,NaN,($/bbl),($/bbl),($/bbl),($/bbl),($/mt),($/mt),($/mmbtu),($/mmbtu),($/mmbtu),...,($/mt),($/dmtu),($/mt),($/mt),($/mt),($/mt),($/mt),($/troy oz),($/troy oz),($/troy oz)
1,1960M01,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,511.471832,11.42,715.4,206.1,2180.4,1631,260.8,35.27,83.5,0.9137
2,1960M02,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,511.471832,11.42,728.19,203.7,2180.4,1631,244.9,35.27,83.5,0.9137
3,1960M03,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,511.471832,11.42,684.94,210.3,2173.8,1631,248.7,35.27,83.5,0.9137
4,1960M04,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,511.471832,11.42,723.11,213.6,2178.2,1631,254.6,35.27,83.5,0.9137

In [ ]:
second_header = df.iloc[0]

In [ ]:
second_header

Unnamed: 0                    NaN
Crude oil, average        ($/bbl)
Crude oil, Brent          ($/bbl)
Crude oil, Dubai          ($/bbl)
Crude oil, WTI            ($/bbl)
                         ...
Nickel                     ($/mt)
Zinc                       ($/mt)
Gold                  ($/troy oz)
Platinum              ($/troy oz)
Silver                ($/troy oz)
Name: 0, Length: 72, dtype: object

In [ ]:
df.columns = [
    f"{col} {second_header[i]}" if pd.notna(second_header[i]) else col
    for i, col in enumerate(df.columns)
]

/tmp/ipython-input-17922274.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  f"{col} {second_header[i]}" if pd.notna(second_header[i]) else col

In [ ]:
df = df.iloc[1:].reset_index(drop=True)

In [ ]:
df.head()

,Unnamed: 0,"Crude oil, average ($/bbl)","Crude oil, Brent ($/bbl)","Crude oil, Dubai ($/bbl)","Crude oil, WTI ($/bbl)","Coal, Australian ($/mt)","Coal, South African ** ($/mt)","Natural gas, US ($/mmbtu)","Natural gas, Europe ($/mmbtu)","Liquefied natural gas, Japan ($/mmbtu)",...,Aluminum ($/mt),"Iron ore, cfr spot ($/dmtu)",Copper ($/mt),Lead ($/mt),Tin ($/mt),Nickel ($/mt),Zinc ($/mt),Gold ($/troy oz),Platinum ($/troy oz),Silver ($/troy oz)
0,1960M01,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,511.471832,11.42,715.4,206.1,2180.4,1631,260.8,35.27,83.5,0.9137
1,1960M02,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,511.471832,11.42,728.19,203.7,2180.4,1631,244.9,35.27,83.5,0.9137
2,1960M03,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,511.471832,11.42,684.94,210.3,2173.8,1631,248.7,35.27,83.5,0.9137
3,1960M04,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,511.471832,11.42,723.11,213.6,2178.2,1631,254.6,35.27,83.5,0.9137
4,1960M05,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,511.471832,11.42,684.75,213.4,2162.7,1631,253.8,35.27,83.5,0.9137

In [ ]:
df_cleaned = df.dropna(subset=['Unnamed: 0']).copy()
df_cleaned = df_cleaned.assign(
    date = lambda x: pd.to_datetime(x['Unnamed: 0'].astype(str).str.replace('M','-', regex=False) + '-01')
)
display(df_cleaned.head())

,Unnamed: 0,"Crude oil, average ($/bbl)","Crude oil, Brent ($/bbl)","Crude oil, Dubai ($/bbl)","Crude oil, WTI ($/bbl)","Coal, Australian ($/mt)","Coal, South African ** ($/mt)","Natural gas, US ($/mmbtu)","Natural gas, Europe ($/mmbtu)","Liquefied natural gas, Japan ($/mmbtu)",...,"Iron ore, cfr spot ($/dmtu)",Copper ($/mt),Lead ($/mt),Tin ($/mt),Nickel ($/mt),Zinc ($/mt),Gold ($/troy oz),Platinum ($/troy oz),Silver ($/troy oz),date
0,1960M01,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,11.42,715.4,206.1,2180.4,1631,260.8,35.27,83.5,0.9137,1960-01-01
1,1960M02,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,11.42,728.19,203.7,2180.4,1631,244.9,35.27,83.5,0.9137,1960-02-01
2,1960M03,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,11.42,684.94,210.3,2173.8,1631,248.7,35.27,83.5,0.9137,1960-03-01
3,1960M04,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,11.42,723.11,213.6,2178.2,1631,254.6,35.27,83.5,0.9137,1960-04-01
4,1960M05,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,11.42,684.75,213.4,2162.7,1631,253.8,35.27,83.5,0.9137,1960-05-01

In [ ]:
cols_to_keep = [
    col for col in df.columns
    if any(keyword in col for keyword in [
        "Crude oil",
        "Natural gas",
        "Copper",
        "Aluminum"
    ])
]

df_filtered = df_cleaned[["date"] + cols_to_keep]

In [ ]:
df_filtered.head()

,date,"Crude oil, average ($/bbl)","Crude oil, Brent ($/bbl)","Crude oil, Dubai ($/bbl)","Crude oil, WTI ($/bbl)","Natural gas, US ($/mmbtu)","Natural gas, Europe ($/mmbtu)",Natural gas index (2010=100),Aluminum ($/mt),Copper ($/mt)
0,1960-01-01,1.63,1.63,1.63,…,0.14,0.404774,…,511.471832,715.4
1,1960-02-01,1.63,1.63,1.63,…,0.14,0.404774,…,511.471832,728.19
2,1960-03-01,1.63,1.63,1.63,…,0.14,0.404774,…,511.471832,684.94
3,1960-04-01,1.63,1.63,1.63,…,0.14,0.404774,…,511.471832,723.11
4,1960-05-01,1.63,1.63,1.63,…,0.14,0.404774,…,511.471832,684.75

In [ ]:
df_filtered = df_filtered.assign(
    year = lambda x: x.date.dt.year,
    month = lambda x: x.date.dt.month,
)

In [ ]:
df_filtered.head()

,date,"Crude oil, average ($/bbl)","Crude oil, Brent ($/bbl)","Crude oil, Dubai ($/bbl)","Crude oil, WTI ($/bbl)","Natural gas, US ($/mmbtu)","Natural gas, Europe ($/mmbtu)",Natural gas index (2010=100),Aluminum ($/mt),Copper ($/mt),year,month
0,1960-01-01,1.63,1.63,1.63,…,0.14,0.404774,…,511.471832,715.4,1960,1
1,1960-02-01,1.63,1.63,1.63,…,0.14,0.404774,…,511.471832,728.19,1960,2
2,1960-03-01,1.63,1.63,1.63,…,0.14,0.404774,…,511.471832,684.94,1960,3
3,1960-04-01,1.63,1.63,1.63,…,0.14,0.404774,…,511.471832,723.11,1960,4
4,1960-05-01,1.63,1.63,1.63,…,0.14,0.404774,…,511.471832,684.75,1960,5

In [ ]:
df_melted = df_filtered.melt(
    id_vars = ['date', 'year', 'month'],
    var_name = 'commodity',
    value_name = 'price'
)

In [ ]:
df_melted['source'] = 'World Bank Pink Sheet'

In [ ]:
df_melted["commodity_clean"] = (
    df_melted["commodity"]
    .str.replace(r"\s*\(.*?\)", "", regex=True)
    .str.strip()
)

In [ ]:
df_melted.head()

,date,year,month,commodity,price,source,commodity_clean
0,1960-01-01,1960,1,"Crude oil, average ($/bbl)",1.63,World Bank Pink Sheet,"Crude oil, average"
1,1960-02-01,1960,2,"Crude oil, average ($/bbl)",1.63,World Bank Pink Sheet,"Crude oil, average"
2,1960-03-01,1960,3,"Crude oil, average ($/bbl)",1.63,World Bank Pink Sheet,"Crude oil, average"
3,1960-04-01,1960,4,"Crude oil, average ($/bbl)",1.63,World Bank Pink Sheet,"Crude oil, average"
4,1960-05-01,1960,5,"Crude oil, average ($/bbl)",1.63,World Bank Pink Sheet,"Crude oil, average"

In [ ]:
df_melted.rename({'price':'nominal_price'}, axis=1, inplace = True)

In [ ]:
df_melted = df_melted.assign(
    unit = lambda x: x.commodity.str.extract(r'\((.*?)\)')
).drop('commodity', axis=1)

In [ ]:
df_melted.head()

,date,year,month,nominal_price,source,commodity_clean,unit
0,1960-01-01,1960,1,1.63,World Bank Pink Sheet,"Crude oil, average",$/bbl
1,1960-02-01,1960,2,1.63,World Bank Pink Sheet,"Crude oil, average",$/bbl
2,1960-03-01,1960,3,1.63,World Bank Pink Sheet,"Crude oil, average",$/bbl
3,1960-04-01,1960,4,1.63,World Bank Pink Sheet,"Crude oil, average",$/bbl
4,1960-05-01,1960,5,1.63,World Bank Pink Sheet,"Crude oil, average",$/bbl

In [ ]:
df_melted.shape[0]

7137

In [ ]:
df_melted.loc[~df_melted.commodity_clean.str.contains('average')]

,date,year,month,nominal_price,source,commodity_clean,unit
793,1960-01-01,1960,1,1.63,World Bank Pink Sheet,"Crude oil, Brent",$/bbl
794,1960-02-01,1960,2,1.63,World Bank Pink Sheet,"Crude oil, Brent",$/bbl
795,1960-03-01,1960,3,1.63,World Bank Pink Sheet,"Crude oil, Brent",$/bbl
796,1960-04-01,1960,4,1.63,World Bank Pink Sheet,"Crude oil, Brent",$/bbl
797,1960-05-01,1960,5,1.63,World Bank Pink Sheet,"Crude oil, Brent",$/bbl
...,...,...,...,...,...,...,...
7132,2025-09-01,2025,9,9983.79,World Bank Pink Sheet,Copper,$/mt
7133,2025-10-01,2025,10,10739.91,World Bank Pink Sheet,Copper,$/mt
7134,2025-11-01,2025,11,10812.03,World Bank Pink Sheet,Copper,$/mt
7135,2025-12-01,2025,12,11785.25,World Bank Pink Sheet,Copper,$/mt
7136,2026-01-01,2026,1,13012,World Bank Pink Sheet,Copper,$/mt

In [ ]:
display(df_melted.head())

,date,year,month,nominal_price,source,commodity_clean,unit
0,1960-01-01,1960,1,1.63,World Bank Pink Sheet,"Crude oil, average",$/bbl
1,1960-02-01,1960,2,1.63,World Bank Pink Sheet,"Crude oil, average",$/bbl
2,1960-03-01,1960,3,1.63,World Bank Pink Sheet,"Crude oil, average",$/bbl
3,1960-04-01,1960,4,1.63,World Bank Pink Sheet,"Crude oil, average",$/bbl
4,1960-05-01,1960,5,1.63,World Bank Pink Sheet,"Crude oil, average",$/bbl

In [ ]:
df_melted[["commodity_family", "commodity_variant"]] = (
    df_melted["commodity_clean"]
    .str.split(",", n=1, expand=True)
)

df_melted["commodity_family"] = df_melted["commodity_family"].str.strip()
df_melted["commodity_variant"] = df_melted["commodity_variant"].str.strip()

In [ ]:
df_melted.head()

,date,year,month,nominal_price,source,commodity_clean,unit,commodity_family,commodity_variant
0,1960-01-01,1960,1,1.63,World Bank Pink Sheet,"Crude oil, average",$/bbl,Crude oil,average
1,1960-02-01,1960,2,1.63,World Bank Pink Sheet,"Crude oil, average",$/bbl,Crude oil,average
2,1960-03-01,1960,3,1.63,World Bank Pink Sheet,"Crude oil, average",$/bbl,Crude oil,average
3,1960-04-01,1960,4,1.63,World Bank Pink Sheet,"Crude oil, average",$/bbl,Crude oil,average
4,1960-05-01,1960,5,1.63,World Bank Pink Sheet,"Crude oil, average",$/bbl,Crude oil,average

In [ ]:
df_melted = df_melted[['date', 'year', 'month', 'commodity_family', 'commodity_variant', 'unit', 'nominal_price', 'source']]

In [ ]:
df_melted.tail()

,date,year,month,commodity_family,commodity_variant,unit,nominal_price,source
7132,2025-09-01,2025,9,Copper,None,$/mt,9983.79,World Bank Pink Sheet
7133,2025-10-01,2025,10,Copper,None,$/mt,10739.91,World Bank Pink Sheet
7134,2025-11-01,2025,11,Copper,None,$/mt,10812.03,World Bank Pink Sheet
7135,2025-12-01,2025,12,Copper,None,$/mt,11785.25,World Bank Pink Sheet
7136,2026-01-01,2026,1,Copper,None,$/mt,13012,World Bank Pink Sheet

In [ ]:
df_melted.to_csv('monthly_world_bank_commodity_prices_1960_2025.csv', index=False)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/monthly_world_bank_commodity_prices_1960_2025.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7137 entries, 0 to 7136
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               7137 non-null   object
 1   year               7137 non-null   int64
 2   month              7137 non-null   int64
 3   commodity_family   7137 non-null   object
 4   commodity_variant  4758 non-null   object
 5   unit               7137 non-null   object
 6   nominal_price      7137 non-null   object
 7   source             7137 non-null   object
dtypes: int64(2), object(6)
memory usage: 446.2+ KB

In [ ]:
df.nominal_price.astype('float')

ValueError: could not convert string to float: '…'

In [ ]:
import numpy as np

s = df['nominal_price'].astype(str).str.strip()
s = s.replace({'..': np.nan, '...': np.nan, '': np.nan})
df['nominal_price'] = pd.to_numeric(s, errors='coerce')

In [ ]:
df.shape

(7137, 8)

In [ ]:
df.loc[lambda x: x.nominal_price.isna()]

,date,year,month,commodity_family,commodity_variant,unit,nominal_price,source
2379,1960-01-01,1960,1,Crude oil,WTI,$/bbl,NaN,World Bank Pink Sheet
2380,1960-02-01,1960,2,Crude oil,WTI,$/bbl,NaN,World Bank Pink Sheet
2381,1960-03-01,1960,3,Crude oil,WTI,$/bbl,NaN,World Bank Pink Sheet
2382,1960-04-01,1960,4,Crude oil,WTI,$/bbl,NaN,World Bank Pink Sheet
2383,1960-05-01,1960,5,Crude oil,WTI,$/bbl,NaN,World Bank Pink Sheet
...,...,...,...,...,...,...,...,...
4957,1976-08-01,1976,8,Natural gas index,NaN,2010=100,NaN,World Bank Pink Sheet
4958,1976-09-01,1976,9,Natural gas index,NaN,2010=100,NaN,World Bank Pink Sheet
4959,1976-10-01,1976,10,Natural gas index,NaN,2010=100,NaN,World Bank Pink Sheet
4960,1976-11-01,1976,11,Natural gas index,NaN,2010=100,NaN,World Bank Pink Sheet
4961,1976-12-01,1976,12,Natural gas index,NaN,2010=100,NaN,World Bank Pink Sheet

In [ ]:
df.drop(df.loc[lambda x: x.nominal_price.isna()].index, axis=0, inplace=True)

In [ ]:
df.reset_index().drop('index', axis=1, inplace=True)

In [ ]:
df.head()

,date,year,month,commodity_family,commodity_variant,unit,nominal_price,source
0,1960-01-01,1960,1,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
1,1960-02-01,1960,2,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
2,1960-03-01,1960,3,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
3,1960-04-01,1960,4,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
4,1960-05-01,1960,5,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet

In [ ]:
df.head(30)

,date,year,month,commodity_family,commodity_variant,unit,nominal_price,source
0,1960-01-01,1960,1,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
1,1960-02-01,1960,2,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
2,1960-03-01,1960,3,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
3,1960-04-01,1960,4,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
4,1960-05-01,1960,5,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
5,1960-06-01,1960,6,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
6,1960-07-01,1960,7,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
7,1960-08-01,1960,8,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
8,1960-09-01,1960,9,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
9,1960-10-01,1960,10,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
10,1960-11-01,1960,11,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
11,1960-12-01,1960,12,Crude oil,average,$/bbl,1.63,World Bank Pink Sheet
12,1961-01-01,1961,1,Crude oil,average,$/bbl,1.57,World Bank Pink Sheet
13,1961-02-01,1961,2,Crude oil,average,$/bbl,1.57,World Bank Pink Sheet
14,1961-03-01,1961,3,Crude oil,average,$/bbl,1.57,World Bank Pink Sheet
15,1961-04-01,1961,4,Crude oil,average,$/bbl,1.57,World Bank Pink Sheet
16,1961-05-01,1961,5,Crude oil,average,$/bbl,1.57,World Bank Pink Sheet
17,1961-06-01,1961,6,Crude oil,average,$/bbl,1.57,World Bank Pink Sheet
18,1961-07-01,1961,7,Crude oil,average,$/bbl,1.57,World Bank Pink Sheet
19,1961-08-01,1961,8,Crude oil,average,$/bbl,1.57,World Bank Pink Sheet
20,1961-09-01,1961,9,Crude oil,average,$/bbl,1.57,World Bank Pink Sheet
21,1961-10-01,1961,10,Crude oil,average,$/bbl,1.57,World Bank Pink Sheet
22,1961-11-01,1961,11,Crude oil,average,$/bbl,1.57,World Bank Pink Sheet
23,1961-12-01,1961,12,Crude oil,average,$/bbl,1.57,World Bank Pink Sheet
24,1962-01-01,1962,1,Crude oil,average,$/bbl,1.52,World Bank Pink Sheet
25,1962-02-01,1962,2,Crude oil,average,$/bbl,1.52,World Bank Pink Sheet
26,1962-03-01,1962,3,Crude oil,average,$/bbl,1.52,World Bank Pink Sheet
27,1962-04-01,1962,4,Crude oil,average,$/bbl,1.52,World Bank Pink Sheet
28,1962-05-01,1962,5,Crude oil,average,$/bbl,1.52,World Bank Pink Sheet
29,1962-06-01,1962,6,Crude oil,average,$/bbl,1.52,World Bank Pink Sheet

In [ ]:
df.loc[df.nominal_price.isna()]

Empty DataFrame
Columns: [date, year, month, commodity_family, commodity_variant, unit, nominal_price, source]
Index: []

In [ ]:
df.shape

(6669, 8)

In [ ]:
df.to_csv('monthly_world_bank_commodity_prices_1960_2025_v2.csv', index=False)